// Country + State/Province/Region data
// Countries without state breakdowns get a free-text region input

export interface Country {
  code: string;
  name: string;
  states?: string[];
}

export const COUNTRIES: Country[] = [
  { code:"AF", name:"Afghanistan" },
  { code:"AL", name:"Albania" },
  { code:"DZ", name:"Algeria", states:["Adrar","Ain Defla","Ain Temouchent","Algiers","Annaba","Batna","Bechar","Bejaia","Biskra","Blida","Bordj Bou Arreridj","Bouira","Boumerdes","Chlef","Constantine","Djelfa","El Bayadh","El Oued","El Tarf","Ghardaia","Guelma","Illizi","Jijel","Khenchela","Laghouat","M'Sila","Mascara","Medea","Mila","Mostaganem","Naama","Oran","Ouargla","Oum El Bouaghi","Relizane","Saida","Setif","Sidi Bel Abbes","Skikda","Souk Ahras","Tamanrasset","Tebessa","Tiaret","Tindouf","Tipaza","Tissemsilt","Tizi Ouzou","Tlemcen"] },
  { code:"AO", name:"Angola" },
  { code:"AG", name:"Antigua and Barbuda" },
  { code:"AR", name:"Argentina", states:["Buenos Aires","Catamarca","Chaco","Chubut","Córdoba","Corrientes","Entre Ríos","Formosa","Jujuy","La Pampa","La Rioja","Mendoza","Misiones","Neuquén","Río Negro","Salta","San Juan","San Luis","Santa Cruz","Santa Fe","Santiago del Estero","Tierra del Fuego","Tucumán"] },
  { code:"AM", name:"Armenia" },
  { code:"AU", name:"Australia", states:["Australian Capital Territory","New South Wales","Northern Territory","Queensland","South Australia","Tasmania","Victoria","Western Australia"] },
  { code:"AT", name:"Austria", states:["Burgenland","Carinthia","Lower Austria","Salzburg","Styria","Tyrol","Upper Austria","Vienna","Vorarlberg"] },
  { code:"AZ", name:"Azerbaijan" },
  { code:"BS", name:"Bahamas" },
  { code:"BH", name:"Bahrain" },
  { code:"BD", name:"Bangladesh", states:["Barisal","Chittagong","Dhaka","Khulna","Mymensingh","Rajshahi","Rangpur","Sylhet"] },
  { code:"BB", name:"Barbados" },
  { code:"BY", name:"Belarus" },
  { code:"BE", name:"Belgium", states:["Brussels","Flanders","Wallonia"] },
  { code:"BZ", name:"Belize" },
  { code:"BJ", name:"Benin", states:["Alibori","Atakora","Atlantique","Borgou","Collines","Donga","Kouffo","Littoral","Mono","Oueme","Plateau","Zou"] },
  { code:"BT", name:"Bhutan" },
  { code:"BO", name:"Bolivia" },
  { code:"BA", name:"Bosnia and Herzegovina" },
  { code:"BW", name:"Botswana" },
  { code:"BR", name:"Brazil", states:["Acre","Alagoas","Amapá","Amazonas","Bahia","Ceará","Distrito Federal","Espírito Santo","Goiás","Maranhão","Mato Grosso","Mato Grosso do Sul","Minas Gerais","Pará","Paraíba","Paraná","Pernambuco","Piauí","Rio de Janeiro","Rio Grande do Norte","Rio Grande do Sul","Rondônia","Roraima","Santa Catarina","São Paulo","Sergipe","Tocantins"] },
  { code:"BN", name:"Brunei" },
  { code:"BG", name:"Bulgaria" },
  { code:"BF", name:"Burkina Faso" },
  { code:"BI", name:"Burundi" },
  { code:"CV", name:"Cabo Verde" },
  { code:"KH", name:"Cambodia" },
  { code:"CM", name:"Cameroon", states:["Adamawa","Centre","East","Far North","Littoral","North","Northwest","South","Southwest","West"] },
  { code:"CA", name:"Canada", states:["Alberta","British Columbia","Manitoba","New Brunswick","Newfoundland and Labrador","Northwest Territories","Nova Scotia","Nunavut","Ontario","Prince Edward Island","Quebec","Saskatchewan","Yukon"] },
  { code:"CF", name:"Central African Republic" },
  { code:"TD", name:"Chad" },
  { code:"CL", name:"Chile", states:["Antofagasta","Araucanía","Arica y Parinacota","Atacama","Aysén","Biobío","Coquimbo","Los Lagos","Los Ríos","Magallanes","Maule","Metropolitana","Ñuble","O'Higgins","Tarapacá","Valparaíso"] },
  { code:"CN", name:"China", states:["Anhui","Beijing","Chongqing","Fujian","Gansu","Guangdong","Guangxi","Guizhou","Hainan","Hebei","Heilongjiang","Henan","Hong Kong","Hubei","Hunan","Inner Mongolia","Jiangsu","Jiangxi","Jilin","Liaoning","Macau","Ningxia","Qinghai","Shaanxi","Shandong","Shanghai","Shanxi","Sichuan","Tianjin","Tibet","Xinjiang","Yunnan","Zhejiang"] },
  { code:"CO", name:"Colombia", states:["Amazonas","Antioquia","Arauca","Atlántico","Bogotá","Bolívar","Boyacá","Caldas","Caquetá","Casanare","Cauca","Cesar","Chocó","Córdoba","Cundinamarca","Guainía","Guaviare","Huila","La Guajira","Magdalena","Meta","Nariño","Norte de Santander","Putumayo","Quindío","Risaralda","San Andrés y Providencia","Santander","Sucre","Tolima","Valle del Cauca","Vaupés","Vichada"] },
  { code:"KM", name:"Comoros" },
  { code:"CG", name:"Congo" },
  { code:"CD", name:"Congo (DRC)" },
  { code:"CR", name:"Costa Rica" },
  { code:"CI", name:"Côte d'Ivoire", states:["Abidjan","Bas-Sassandra","Comoé","Denguélé","Gôh-Djiboua","Lacs","Lagunes","Montagnes","Sassandra-Marahoué","Savanes","Vallée du Bandama","Woroba","Yamoussoukro","Zanzan"] },
  { code:"HR", name:"Croatia" },
  { code:"CU", name:"Cuba" },
  { code:"CY", name:"Cyprus" },
  { code:"CZ", name:"Czech Republic" },
  { code:"DK", name:"Denmark" },
  { code:"DJ", name:"Djibouti" },
  { code:"DM", name:"Dominica" },
  { code:"DO", name:"Dominican Republic" },
  { code:"EC", name:"Ecuador" },
  { code:"EG", name:"Egypt", states:["Alexandria","Aswan","Asyut","Beheira","Beni Suef","Cairo","Dakahlia","Damietta","Faiyum","Gharbia","Giza","Ismailia","Kafr el-Sheikh","Luxor","Matruh","Minya","Monufia","New Valley","North Sinai","Port Said","Qalyubia","Qena","Red Sea","Sharqia","Sohag","South Sinai","Suez"] },
  { code:"SV", name:"El Salvador" },
  { code:"GQ", name:"Equatorial Guinea" },
  { code:"ER", name:"Eritrea" },
  { code:"EE", name:"Estonia" },
  { code:"SZ", name:"Eswatini" },
  { code:"ET", name:"Ethiopia", states:["Addis Ababa","Afar","Amhara","Benishangul-Gumuz","Dire Dawa","Gambela","Harari","Oromia","Sidama","SNNPR","Somali","Tigray"] },
  { code:"FJ", name:"Fiji" },
  { code:"FI", name:"Finland" },
  { code:"FR", name:"France", states:["Auvergne-Rhône-Alpes","Bourgogne-Franche-Comté","Bretagne","Centre-Val de Loire","Corse","Grand Est","Guadeloupe","Guyane","Hauts-de-France","Île-de-France","La Réunion","Martinique","Mayotte","Normandie","Nouvelle-Aquitaine","Occitanie","Pays de la Loire","Provence-Alpes-Côte d'Azur"] },
  { code:"GA", name:"Gabon" },
  { code:"GM", name:"Gambia" },
  { code:"GE", name:"Georgia" },
  { code:"DE", name:"Germany", states:["Baden-Württemberg","Bavaria","Berlin","Brandenburg","Bremen","Hamburg","Hesse","Lower Saxony","Mecklenburg-Vorpommern","North Rhine-Westphalia","Rhineland-Palatinate","Saarland","Saxony","Saxony-Anhalt","Schleswig-Holstein","Thuringia"] },
  { code:"GH", name:"Ghana", states:["Ahafo","Ashanti","Bono","Bono East","Central","Eastern","Greater Accra","North East","Northern","Oti","Savannah","Upper East","Upper West","Volta","Western","Western North"] },
  { code:"GR", name:"Greece" },
  { code:"GT", name:"Guatemala" },
  { code:"GN", name:"Guinea" },
  { code:"GW", name:"Guinea-Bissau" },
  { code:"GY", name:"Guyana" },
  { code:"HT", name:"Haiti" },
  { code:"HN", name:"Honduras" },
  { code:"HU", name:"Hungary" },
  { code:"IS", name:"Iceland" },
  { code:"IN", name:"India", states:["Andaman and Nicobar Islands","Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chandigarh","Chhattisgarh","Dadra and Nagar Haveli and Daman and Diu","Delhi","Goa","Gujarat","Haryana","Himachal Pradesh","Jammu and Kashmir","Jharkhand","Karnataka","Kerala","Ladakh","Lakshadweep","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Puducherry","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal"] },
  { code:"ID", name:"Indonesia", states:["Aceh","Bali","Bangka Belitung","Banten","Bengkulu","Central Java","Central Kalimantan","Central Sulawesi","East Java","East Kalimantan","East Nusa Tenggara","Gorontalo","Jakarta","Jambi","Lampung","Maluku","North Kalimantan","North Maluku","North Sulawesi","North Sumatra","Papua","Riau","Riau Islands","Southeast Sulawesi","South Kalimantan","South Sulawesi","South Sumatra","West Java","West Kalimantan","West Nusa Tenggara","West Papua","West Sulawesi","West Sumatra","Yogyakarta"] },
  { code:"IR", name:"Iran" },
  { code:"IQ", name:"Iraq" },
  { code:"IE", name:"Ireland" },
  { code:"IL", name:"Israel" },
  { code:"IT", name:"Italy", states:["Abruzzo","Aosta Valley","Apulia","Basilicata","Calabria","Campania","Emilia-Romagna","Friuli-Venezia Giulia","Lazio","Liguria","Lombardy","Marche","Molise","Piedmont","Sardinia","Sicily","Trentino-South Tyrol","Tuscany","Umbria","Veneto"] },
  { code:"JM", name:"Jamaica" },
  { code:"JP", name:"Japan", states:["Aichi","Akita","Aomori","Chiba","Ehime","Fukui","Fukuoka","Fukushima","Gifu","Gunma","Hiroshima","Hokkaido","Hyogo","Ibaraki","Ishikawa","Iwate","Kagawa","Kagoshima","Kanagawa","Kochi","Kumamoto","Kyoto","Mie","Miyagi","Miyazaki","Nagano","Nagasaki","Nara","Niigata","Oita","Okayama","Okinawa","Osaka","Saga","Saitama","Shiga","Shimane","Shizuoka","Tochigi","Tokushima","Tokyo","Tottori","Toyama","Wakayama","Yamagata","Yamaguchi","Yamanashi"] },
  { code:"JO", name:"Jordan" },
  { code:"KZ", name:"Kazakhstan" },
  { code:"KE", name:"Kenya", states:["Baringo","Bomet","Bungoma","Busia","Elgeyo-Marakwet","Embu","Garissa","Homa Bay","Isiolo","Kajiado","Kakamega","Kericho","Kiambu","Kilifi","Kirinyaga","Kisii","Kisumu","Kitui","Kwale","Laikipia","Lamu","Machakos","Makueni","Mandera","Marsabit","Meru","Migori","Mombasa","Murang'a","Nairobi","Nakuru","Nandi","Narok","Nyamira","Nyandarua","Nyeri","Samburu","Siaya","Taita-Taveta","Tana River","Tharaka-Nithi","Trans-Nzoia","Turkana","Uasin Gishu","Vihiga","Wajir","West Pokot"] },
  { code:"KI", name:"Kiribati" },
  { code:"KW", name:"Kuwait" },
  { code:"KG", name:"Kyrgyzstan" },
  { code:"LA", name:"Laos" },
  { code:"LV", name:"Latvia" },
  { code:"LB", name:"Lebanon" },
  { code:"LS", name:"Lesotho" },
  { code:"LR", name:"Liberia" },
  { code:"LY", name:"Libya" },
  { code:"LI", name:"Liechtenstein" },
  { code:"LT", name:"Lithuania" },
  { code:"LU", name:"Luxembourg" },
  { code:"MG", name:"Madagascar" },
  { code:"MW", name:"Malawi", states:["Central Region","Northern Region","Southern Region"] },
  { code:"MY", name:"Malaysia", states:["Johor","Kedah","Kelantan","Kuala Lumpur","Labuan","Melaka","Negeri Sembilan","Pahang","Penang","Perak","Perlis","Putrajaya","Sabah","Sarawak","Selangor","Terengganu"] },
  { code:"MV", name:"Maldives" },
  { code:"ML", name:"Mali" },
  { code:"MT", name:"Malta" },
  { code:"MH", name:"Marshall Islands" },
  { code:"MR", name:"Mauritania" },
  { code:"MU", name:"Mauritius" },
  { code:"MX", name:"Mexico", states:["Aguascalientes","Baja California","Baja California Sur","Campeche","Chiapas","Chihuahua","Ciudad de México","Coahuila","Colima","Durango","Guanajuato","Guerrero","Hidalgo","Jalisco","México","Michoacán","Morelos","Nayarit","Nuevo León","Oaxaca","Puebla","Querétaro","Quintana Roo","San Luis Potosí","Sinaloa","Sonora","Tabasco","Tamaulipas","Tlaxcala","Veracruz","Yucatán","Zacatecas"] },
  { code:"FM", name:"Micronesia" },
  { code:"MD", name:"Moldova" },
  { code:"MC", name:"Monaco" },
  { code:"MN", name:"Mongolia" },
  { code:"ME", name:"Montenegro" },
  { code:"MA", name:"Morocco" },
  { code:"MZ", name:"Mozambique", states:["Cabo Delgado","Gaza","Inhambane","Manica","Maputo","Maputo City","Nampula","Niassa","Sofala","Tete","Zambezia"] },
  { code:"MM", name:"Myanmar" },
  { code:"NA", name:"Namibia" },
  { code:"NR", name:"Nauru" },
  { code:"NP", name:"Nepal" },
  { code:"NL", name:"Netherlands" },
  { code:"NZ", name:"New Zealand", states:["Auckland","Bay of Plenty","Canterbury","Gisborne","Hawke's Bay","Manawatu-Whanganui","Marlborough","Nelson","Northland","Otago","Southland","Taranaki","Tasman","Waikato","Wellington","West Coast"] },
  { code:"NI", name:"Nicaragua" },
  { code:"NE", name:"Niger" },
  { code:"NG", name:"Nigeria", states:["Abia","Adamawa","Akwa Ibom","Anambra","Bauchi","Bayelsa","Benue","Borno","Cross River","Delta","Ebonyi","Edo","Ekiti","Enugu","FCT","Gombe","Imo","Jigawa","Kaduna","Kano","Katsina","Kebbi","Kogi","Kwara","Lagos","Nasarawa","Niger","Ogun","Ondo","Osun","Oyo","Plateau","Rivers","Sokoto","Taraba","Yobe","Zamfara"] },
  { code:"NO", name:"Norway" },
  { code:"OM", name:"Oman" },
  { code:"PK", name:"Pakistan", states:["Azad Kashmir","Balochistan","Gilgit-Baltistan","Islamabad","Khyber Pakhtunkhwa","Punjab","Sindh"] },
  { code:"PW", name:"Palau" },
  { code:"PA", name:"Panama" },
  { code:"PG", name:"Papua New Guinea" },
  { code:"PY", name:"Paraguay" },
  { code:"PE", name:"Peru", states:["Amazonas","Ancash","Apurímac","Arequipa","Ayacucho","Cajamarca","Callao","Cusco","Huancavelica","Huánuco","Ica","Junín","La Libertad","Lambayeque","Lima","Loreto","Madre de Dios","Moquegua","Pasco","Piura","Puno","San Martín","Tacna","Tumbes","Ucayali"] },
  { code:"PH", name:"Philippines", states:["Abra","Agusan del Norte","Agusan del Sur","Aklan","Albay","Antique","Apayao","Aurora","Basilan","Bataan","Batanes","Batangas","Benguet","Biliran","Bohol","Bukidnon","Bulacan","Cagayan","Camarines Norte","Camarines Sur","Camiguin","Capiz","Catanduanes","Cavite","Cebu","Compostela Valley","Cotabato","Davao del Norte","Davao del Sur","Davao Occidental","Davao Oriental","Dinagat Islands","Eastern Samar","Guimaras","Ifugao","Ilocos Norte","Ilocos Sur","Iloilo","Isabela","Kalinga","La Union","Laguna","Lanao del Norte","Lanao del Sur","Leyte","Maguindanao","Marinduque","Masbate","Metro Manila","Misamis Occidental","Misamis Oriental","Mountain Province","Negros Occidental","Negros Oriental","Northern Samar","Nueva Ecija","Nueva Vizcaya","Occidental Mindoro","Oriental Mindoro","Palawan","Pampanga","Pangasinan","Quezon","Quirino","Rizal","Romblon","Samar","Sarangani","Shariff Kabunsuan","Siquijor","Sorsogon","South Cotabato","Southern Leyte","Sultan Kudarat","Sulu","Surigao del Norte","Surigao del Sur","Tarlac","Tawi-Tawi","Zambales","Zamboanga del Norte","Zamboanga del Sur","Zamboanga Sibugay"] },
  { code:"PL", name:"Poland" },
  { code:"PT", name:"Portugal" },
  { code:"QA", name:"Qatar" },
  { code:"RO", name:"Romania" },
  { code:"RU", name:"Russia", states:["Adygea","Altai Krai","Altai Republic","Amur Oblast","Arkhangelsk Oblast","Astrakhan Oblast","Bashkortostan","Belgorod Oblast","Bryansk Oblast","Buryatia","Chechen Republic","Chelyabinsk Oblast","Chukotka","Chuvashia","Dagestan","Ingushetia","Irkutsk Oblast","Ivanovo Oblast","Jewish AO","Kabardino-Balkaria","Kaliningrad Oblast","Kalmykia","Kaluga Oblast","Kamchatka Krai","Karachay-Cherkessia","Karelia","Kemerovo Oblast","Khabarovsk Krai","Khakassia","Khanty-Mansi AO","Kirov Oblast","Komi","Kostroma Oblast","Krasnodar Krai","Krasnoyarsk Krai","Kurgan Oblast","Kursk Oblast","Leningrad Oblast","Lipetsk Oblast","Magadan Oblast","Mari El","Mordovia","Moscow","Moscow Oblast","Murmansk Oblast","Nenets AO","Nizhny Novgorod Oblast","North Ossetia","Novgorod Oblast","Novosibirsk Oblast","Omsk Oblast","Orenburg Oblast","Oryol Oblast","Penza Oblast","Perm Krai","Primorsky Krai","Pskov Oblast","Rostov Oblast","Ryazan Oblast","Sakha Republic","Sakhalin Oblast","Samara Oblast","Saratov Oblast","Smolensk Oblast","St. Petersburg","Stavropol Krai","Sverdlovsk Oblast","Tambov Oblast","Tatarstan","Tomsk Oblast","Tula Oblast","Tuva","Tver Oblast","Tyumen Oblast","Udmurtia","Ulyanovsk Oblast","Vladimir Oblast","Volgograd Oblast","Vologda Oblast","Voronezh Oblast","Yamalo-Nenets AO","Yaroslavl Oblast","Zabaykalsky Krai"] },
  { code:"RW", name:"Rwanda", states:["Eastern Province","Kigali","Northern Province","Southern Province","Western Province"] },
  { code:"KN", name:"Saint Kitts and Nevis" },
  { code:"LC", name:"Saint Lucia" },
  { code:"VC", name:"Saint Vincent and the Grenadines" },
  { code:"WS", name:"Samoa" },
  { code:"SM", name:"San Marino" },
  { code:"ST", name:"São Tomé and Príncipe" },
  { code:"SA", name:"Saudi Arabia", states:["Al-Bahah","Al-Jawf","Al-Madinah","Al-Qassim","Asir","Eastern Province","Ha'il","Jizan","Mecca","Najran","Northern Borders","Riyadh","Tabuk"] },
  { code:"SN", name:"Senegal" },
  { code:"RS", name:"Serbia" },
  { code:"SC", name:"Seychelles" },
  { code:"SL", name:"Sierra Leone" },
  { code:"SG", name:"Singapore" },
  { code:"SK", name:"Slovakia" },
  { code:"SI", name:"Slovenia" },
  { code:"SB", name:"Solomon Islands" },
  { code:"SO", name:"Somalia" },
  { code:"ZA", name:"South Africa", states:["Eastern Cape","Free State","Gauteng","KwaZulu-Natal","Limpopo","Mpumalanga","North West","Northern Cape","Western Cape"] },
  { code:"SS", name:"South Sudan" },
  { code:"ES", name:"Spain", states:["Andalusia","Aragon","Asturias","Balearic Islands","Basque Country","Canary Islands","Cantabria","Castile and León","Castile-La Mancha","Catalonia","Ceuta","Extremadura","Galicia","La Rioja","Madrid","Melilla","Murcia","Navarre","Valencia"] },
  { code:"LK", name:"Sri Lanka" },
  { code:"SD", name:"Sudan" },
  { code:"SR", name:"Suriname" },
  { code:"SE", name:"Sweden" },
  { code:"CH", name:"Switzerland" },
  { code:"SY", name:"Syria" },
  { code:"TW", name:"Taiwan" },
  { code:"TJ", name:"Tajikistan" },
  { code:"TZ", name:"Tanzania", states:["Arusha","Dar es Salaam","Dodoma","Geita","Iringa","Kagera","Katavi","Kigoma","Kilimanjaro","Lindi","Manyara","Mara","Mbeya","Morogoro","Mtwara","Mwanza","Njombe","Pemba North","Pemba South","Pwani","Rukwa","Ruvuma","Shinyanga","Simiyu","Singida","Songwe","Tabora","Tanga","Zanzibar North","Zanzibar South","Zanzibar West"] },
  { code:"TH", name:"Thailand", states:["Amnat Charoen","Ang Thong","Bangkok","Bueng Kan","Buriram","Chachoengsao","Chai Nat","Chaiyaphum","Chanthaburi","Chiang Mai","Chiang Rai","Chon Buri","Chumphon","Kalasin","Kamphaeng Phet","Kanchanaburi","Khon Kaen","Krabi","Lampang","Lamphun","Loei","Lop Buri","Mae Hong Son","Maha Sarakham","Mukdahan","Nakhon Nayok","Nakhon Pathom","Nakhon Phanom","Nakhon Ratchasima","Nakhon Sawan","Nakhon Si Thammarat","Nan","Narathiwat","Nong Bua Lamphu","Nong Khai","Nonthaburi","Pathum Thani","Pattani","Phangnga","Phatthalung","Phayao","Phetchabun","Phetchaburi","Phichit","Phitsanulok","Phra Nakhon Si Ayutthaya","Phrae","Phuket","Prachin Buri","Prachuap Khiri Khan","Ranong","Ratchaburi","Rayong","Roi Et","Sa Kaeo","Sakon Nakhon","Samut Prakan","Samut Sakhon","Samut Songkhram","Saraburi","Satun","Sing Buri","Sisaket","Songkhla","Sukhothai","Suphan Buri","Surat Thani","Surin","Tak","Trang","Trat","Ubon Ratchathani","Udon Thani","Uthai Thani","Uttaradit","Yala","Yasothon"] },
  { code:"TL", name:"Timor-Leste" },
  { code:"TG", name:"Togo" },
  { code:"TO", name:"Tonga" },
  { code:"TT", name:"Trinidad and Tobago" },
  { code:"TN", name:"Tunisia" },
  { code:"TR", name:"Turkey", states:["Adana","Adıyaman","Afyonkarahisar","Ağrı","Aksaray","Amasya","Ankara","Antalya","Ardahan","Artvin","Aydın","Balıkesir","Bartın","Batman","Bayburt","Bilecik","Bingöl","Bitlis","Bolu","Burdur","Bursa","Çanakkale","Çankırı","Çorum","Denizli","Diyarbakır","Düzce","Edirne","Elazığ","Erzincan","Erzurum","Eskişehir","Gaziantep","Giresun","Gümüşhane","Hakkari","Hatay","Iğdır","Isparta","Istanbul","İzmir","Kahramanmaraş","Karabük","Karaman","Kars","Kastamonu","Kayseri","Kırıkkale","Kırklareli","Kırşehir","Kilis","Kocaeli","Konya","Kütahya","Malatya","Manisa","Mardin","Mersin","Muğla","Muş","Nevşehir","Niğde","Ordu","Osmaniye","Rize","Sakarya","Samsun","Şanlıurfa","Siirt","Sinop","Sivas","Şırnak","Tekirdağ","Tokat","Trabzon","Tunceli","Uşak","Van","Yalova","Yozgat","Zonguldak"] },
  { code:"TM", name:"Turkmenistan" },
  { code:"TV", name:"Tuvalu" },
  { code:"UG", name:"Uganda", states:["Bugiri","Bukwo","Bulambuli","Bundibugyo","Bunyangabu","Bushenyi","Busia","Butaleja","Butebo","Buyende","Gomba","Gulu","Hoima","Ibanda","Iganga","Isingiro","Jinja","Kaabong","Kabale","Kabarole","Kaberamaido","Kagadi","Kakumiro","Kalaki","Kalangala","Kaliro","Kalungu","Kampala","Kamuli","Kamwenge","Kanungu","Kapchorwa","Kasese","Kasanda","Katakwi","Kayunga","Kibaale","Kiboga","Kibuku","Kikuube","Kiruhura","Kiryandongo","Kisoro","Kitagwenda","Kitgum","Koboko","Kole","Kotido","Kumi","Kwania","Kyankwanzi","Kyegegwa","Kyenjojo","Kyotera","Lamwo","Lira","Luuka","Luweero","Lwengo","Lyantonde","Madi-Okollo","Manafwa","Maracha","Masaka","Masindi","Mayuge","Mbale","Mbarara","Mitooma","Mityana","Moroto","Moyo","Mpigi","Mubende","Mukono","Nabilatuk","Nakapiripirit","Nakaseke","Nakasongola","Namayingo","Namisindwa","Namutumba","Napak","Nebbi","Ngora","Ntoroko","Ntungamo","Nwoya","Obongi","Omoro","Otuke","Oyam","Pader","Pakwach","Pallisa","Rakai","Rubanda","Rubirizi","Rukiga","Rukungiri","Rwampara","Sembabule","Serere","Sheema","Sironko","Soroti","Tororo","Wakiso","Yumbe","Zombo"] },
  { code:"UA", name:"Ukraine" },
  { code:"AE", name:"United Arab Emirates", states:["Abu Dhabi","Ajman","Dubai","Fujairah","Ras al-Khaimah","Sharjah","Umm al-Quwain"] },
  { code:"GB", name:"United Kingdom", states:["England","Northern Ireland","Scotland","Wales"] },
  { code:"US", name:"United States", states:["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","Washington DC","West Virginia","Wisconsin","Wyoming"] },
  { code:"UY", name:"Uruguay" },
  { code:"UZ", name:"Uzbekistan" },
  { code:"VU", name:"Vanuatu" },
  { code:"VE", name:"Venezuela" },
  { code:"VN", name:"Vietnam", states:["An Giang","Ba Ria-Vung Tau","Bac Giang","Bac Kan","Bac Lieu","Bac Ninh","Ben Tre","Binh Dinh","Binh Duong","Binh Phuoc","Binh Thuan","Ca Mau","Can Tho","Cao Bang","Da Nang","Dak Lak","Dak Nong","Dien Bien","Dong Nai","Dong Thap","Gia Lai","Ha Giang","Ha Nam","Ha Noi","Ha Tinh","Hai Duong","Hai Phong","Hau Giang","Hoa Binh","Ho Chi Minh","Hung Yen","Khanh Hoa","Kien Giang","Kon Tum","Lai Chau","Lam Dong","Lang Son","Lao Cai","Long An","Nam Dinh","Nghe An","Ninh Binh","Ninh Thuan","Phu Tho","Phu Yen","Quang Binh","Quang Nam","Quang Ngai","Quang Ninh","Quang Tri","Soc Trang","Son La","Tay Ninh","Thai Binh","Thai Nguyen","Thanh Hoa","Thua Thien-Hue","Tien Giang","Tra Vinh","Tuyen Quang","Vinh Long","Vinh Phuc","Yen Bai"] },
  { code:"YE", name:"Yemen" },
  { code:"ZM", name:"Zambia", states:["Central","Copperbelt","Eastern","Luapula","Lusaka","Muchinga","Northern","North-Western","Southern","Western"] },
  { code:"ZW", name:"Zimbabwe", states:["Bulawayo","Harare","Manicaland","Mashonaland Central","Mashonaland East","Mashonaland West","Masvingo","Matabeleland North","Matabeleland South","Midlands"] },
];

export function getCountry(code: string): Country | undefined {
  return COUNTRIES.find(c => c.code === code);
}
